---
title: "Sample Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source: embed
    runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(p8105.datasets)
library(plotly)
library(flexdashboard)



## Initial cleaning to snake case 

## Selects columns of interest, filters only inspection data from 2015

rest_inspec_df=
  rest_inspec|>
  janitor::clean_names()|>
  drop_na(grade)|>
  filter(str_detect(inspection_date, "2015"))|>
  filter(grade != "P")|>
  select(-census_tract, -community_board, -council_district, -bin, -bbl, -nta, -action, -violation_description, -building, -street, -phone)
```

Row {data-height=225}
-----------------------------------------------------------------------

### Overview

The New York City Department of Health and Mental Hygiene (DOHMH) conducts annual restaurant inspections. This data is publicly available at [NYC Open Data](https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j/about_data) and is updated regularly. The *DOHMH New York City Restaurant Inspection Results* dataset I used was accessed in October 2017 and I imported it from the course, *Data Science I*. 

For the following products, I filtered the data to only include inspections performed in 2015 and those that received the inspection grades *A*, *B*, or *C*. These graphs were created using Plotly to visualize the restaurant locations, frequency of letter grades, and distribution of inspection scores for each borough.\

**Figure 1.**
This scatterplot contains the locations of NYC restaurants inspected in 2015. The latitude is on the x-axis and the longitude is on the y-axis. As indicated in the legend, each borough is represented by a distinct color. For more information, hover over an individual point to view the restaurant's coordinates, identifier, business name, and type of cuisine.

**Figure 2.**
This bar chart contains the frequency of inspection grades by borough. The inspection grades are on the x-axis and the frequency of each grade is on the y-axis. 

**Figure 3.**
This figure contains the distribution of scores for each inspection grade. Throughout restaurant inspections, scores were based on the presence of regulation violations and their severity. These scores were used to determine the inspection grade, with a higher score corresponding to a lower letter grade. For more information, hover over each boxplot to view the values of the minimum, maximum, median, and interquartile range.


Row {data-height=400}
-----------------------------------------------------------------------


### **Figure 1.**

```{r}
rest_inspec_df |>
  drop_na(latitude, longitude)|>
  filter(latitude !="0")|>
  group_by(camis)|>
  mutate(
    text_label = str_c("Restaurant Identifier: ", camis, "\nName of Business: ", dba,
      "\nType of Cuisine: ", cuisine_description)
    )|>
  plot_ly(
    x = ~latitude, y = ~longitude, 
    text = ~text_label, color = ~boro, 
    type = "scatter", colors = "Dark2", mode = "markers", alpha = 0.5)|>
  layout(title = "Restaurant Locations")
```


### **Figure 2.**


```{r}
tab3= 
rest_inspec_df|>
  group_by(grade, boro)|>
  summarize("Grade Count" = n_distinct(camis))|>
  pivot_wider(
    names_from = grade,
    values_from = "Grade Count"
  )

tab3|>
    pivot_longer(
    cols = A:C,
    names_to = "grade",
    values_to = "count"
  )|>
  plot_ly(x = ~grade, y = ~count, color = ~boro, type = "bar", colors = "Dark2")|>
  layout(title = "Inspection Grades by Borough", xaxis = list(title = "Inspection Grades"), yaxis = list(title = "Frequency"))
```


### **Figure 3.**


```{r}

rest_inspec_df |>
  plot_ly(x = ~grade, y = ~score,
         color = ~boro, type = "box", colors = "Dark2")|>
    layout(boxmode = "group", title = "Distribution of 2015 Inspection Scores",
         xaxis = list(title ="Inspection Grades"),
         yaxis = list(title = "Score"))

```





